version: "3.9"

services:
  web:
    container_name: web
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/opt/app/
    ports:
      - "8000:8000"
    depends_on:
      - db


  db:
    container_name: db
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
    postgres_data:

